### PR TITLE
Make specified versions style consistent with each other

### PR DESCRIPTION
**Pull request by bocharsky-bw**
The same style is used in `require` section and this style is used in Symfony packages

### CODE REVIEW

**Comment by stof** [comment]
I don't see the need for that (especially when switching from the current Composer recommendation to the old style of constraints)

**Comment by bocharsky-bw** [comment]
What about revert this line back and tweaked this one:
https://github.com/bocharsky-bw/StofDoctrineExtensionsBundle/blob/f2e89ac761605315b07feacfd63e28216d566ae2/composer.json#L16

to `"symfony/framework-bundle": "~2.7 || ~3.2 || ~4.0",` just to be consistent?

**Comment by bocharsky-bw** [comment]
I mean, this bundle have 2 different styles in `composer.json` for now, I just want to make it consistent

**Comment by stof** [comment]
#403 made the styles consistent when changing the constraints.

**Pull request closed without merging**
