### PR TITLE
configuration-block's in .rst not working

### PR DESCRIPTION
**Pull request by jhcasado**
I see this is happening for FOSUserBundle/Resources/doc/* too, so... the entire github?

### CODE REVIEW

**Comment by stof** [comment]
@javiereguiluz you added configuration blocks in our doc, but the bundle doc is not rendered on symfony.com. Is there plans to add this bundle or should I merge this PR to make the doc compatible with github rendering again ?

**Comment by javiereguiluz** [comment]
I'm sorry for the slow response. I'm going to try to publish this bundle's doc on symfony.com before the end of this week.

**Comment by javiereguiluz** [comment]
I'm sorry for the slow response. I'm going to try to publish this bundle's doc on symfony.com before the end of this week.

**Comment by qcmnagai** [comment]
+1

**Comment by jorrit** [comment]
I hope this gets fixed soon!

**Comment by stof** [comment]
Documentation is now available on http://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html

**Pull request closed without merging**
