### PR TITLE
Symfony 4 compatibility

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by weaverryan** [comment]
Ping!

**Comment by iluuu1994** [comment]
When will this be accepted?

**Comment by zolex** [comment]
please also update gedmo extensions to ^2.4

**Comment by iluuu1994** [comment]
@zolex The constraint is `^2.3.1` which is just another way of saying `>= 2.3.1 <3.0.0` so `2.4` is already included.

**Comment by zolex** [comment]
@iluuu1994 ah okay, I assumed it was a regexp like notation.

**Comment by lucasmezencio** [comment]
Oh please merge this!

**Comment by stayeronglass** [comment]
ping

**Comment by stof** [comment]
closing as I merged #358

**Pull request closed without merging**
