### PR TITLE
Add support for symfony 3

### PR DESCRIPTION
**Pull request by shieldo**
There don't seem to be any additional changes needed for support.

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1: 

ping @stof Seems ready to merge

**Comment by Sharom** [comment]
:+1:

**Comment by stof** [comment]
Thank you @shieldo.

**Comment by kbond** [comment]
Can we get a new tag?

**Comment by WouterJ** [comment]
@kbond @stof promised to release new versions (with Sf3 support) of the libraries he maintains soon after SymfonyCon.

**Comment by kbond** [comment]
Ah, great!

**Pull request merged**
