### PR TITLE
Allowing doctrine-extensions v3

### LINKED ISSUE #413: Installation fails on Symfony 5.1
Hi, I'm trying to install this package on a fresh install of Symfony 5.1 but it fails. Anyone having the issue as well? Thanks

### LINKED ISSUE #414: Support for gedmo/doctrine-extensions 3.0 betas
There was a beta of `gedmo/doctrine-extensions` released two weeks ago (beta2 actually, but it seems the original beta tag was just a mistake).
I'm working on a project where composer requirements conflict with each other unless I install that beta. But this bundle depends specifically on 2.*. I've worked the problem around for myself by depending on my fork which requires the beta instead, but I would love it if I could depend on an upstream tag instead, even if it were a beta tag as well.

### PR DESCRIPTION
**Pull request by Bukashk0zzz**
Fixes #413 and fixes #414

Because #415 not updated for some time I create this request with a fixed constraint.

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
@stof could this be tagged as a new stable release?

**Comment by stof** [comment]
@rimas-kudelis I'm on it.

**Comment by weaverryan** [comment]
Thank you for finishing my PR!

**Comment by weaverryan** [comment]
And thanks Stof for the release :)

**Pull request merged**
