### PR TITLE
v2.4.0 of DoctrineExtensions released

### PR DESCRIPTION
**Pull request by nurikabe**

### CODE REVIEW

**Comment by tubssp** [comment]
+1

**Comment by guilhermeblanco** [comment]
@stof can you please review, merge and tag 1.2.0?

**Comment by cevou** [comment]
+1, i think this needs to be done soon

**Comment by francoispluchino** [comment]
@guilhermeblanco It may be preferable to put a less restrictive constraint: `~2.3.1,<2.5` and tagger the bundle to `v1.1.1`.

@stof Is it possible to make this change? Because there is a fix in the `2.4` version for Doctrine `2.5.0`.

**Comment by djandyr** [comment]
+1

**Comment by shieldo** [comment]
:+1:

**Comment by smartinsalmeida** [comment]
+1

**Comment by drAlberT** [comment]
:+1:

**Comment by notrix** [comment]
:+1:

**Comment by sergej-kurakin** [comment]
+1

**Comment by drAlberT** [comment]
@stof any chance to have this PR merged? :) We are all anxious to update ;)

**Comment by Isabek** [comment]
@stof could you update?

**Comment by gffranco** [comment]
+1

**Comment by futurevision** [comment]
+1

**Comment by cmodijk** [comment]
+1

**Comment by Vincz** [comment]
+1

**Comment by aramalipoor** [comment]
:+1:

**Comment by rolebi** [comment]
:+1: The bug fix on Slug `unique_base` for relation is waiting : )

**Comment by cdaguerre** [comment]
@stof Are you waiting for other PRs to be merged prior to this one?
Any sign of life would be appreciated...

**Pull request closed without merging**
